--[[
[metadata]
description=IUP primitives generated by the Helium library
version=1.0.0
owner=helium|1.1.1
type=lua
created=2025-06-01
]]--

local file_args = {...}

local public = file_args[1]
local private = file_args[2]
local config = file_args[3]

local he = {} -->>public.primitives._func()



--todo: replace assert() with cerr()?



--transparent frame template
he.clearframe = function(intable)
	assert(type(intable) == "table", "Helium.clearframe expects a table for its argument, got a " .. type(intable))
	
	local default = {
		image = private.tryfile("solidframe.png"),
		bgcolor = "0 0 0 0 *",
		segmented = "0 0 1 1",
		iup.vbox { },
		expand = "NO",
	}
	
	for k, v in pairs(intable) do
		default[k] = v
	end
	assert((iup.IsValid(default[1])), "Helium.clearframe input table did not have a valid IUP element at [1]; got " .. type(intable[1]))
	
	return iup.frame(default)
end



--very simple opaque panel
he.solidframe = function(intable)
	assert(type(intable) == "table", "Helium.solidframe expects a table for its argument, got a " .. type(intable))
	
	local default = {
		image = private.tryfile("solidframe.png"),
		bgcolor = "255 255 255 255 *",
		segmented = "0.1 0.1 0.9 0.9",
		iup.vbox { },
		expand = "NO",
	}
	
	for k, v in pairs(intable) do
		default[k] = v
	end
	assert((iup.IsValid(default[1])), "Helium.solidframe input table did not have a valid IUP element at [1]; got " .. type(intable[1]))
	
	return iup.frame(default)
end



--very simple edge frame
he.borderframe = function(intable)
	assert(type(intable) == "table", "Helium.borderframe expects a table for its argument, got a " .. type(intable))
	
	local default = {
		image = private.tryfile("borderframe.png"),
		bgcolor = "255 255 255 255 *",
		segmented = "0.1 0.1 0.9 0.9",
		iup.vbox { },
		expand = "NO",
	}
	
	for k, v in pairs(intable) do
		default[k] = v
	end
	
	assert((iup.IsValid(default[1])), "Helium.borderframe input table did not have a valid IUP element at [1]; got " .. type(intable[1]))
	
	return iup.frame(default)
end



--primitive object used for highlite rules (hover on mouseover stuff), controlled by parent
he.highlite_panel = function()
	local highlite_obj = iup.label {
		title = "",
		image = private.tryfile("solidframe.png"),
		bgcolor = "255 255 255 0 *",
		expand = "YES",
		highlite = function(self)
			self.bgcolor = "255 255 255 255 *"
		end,
		clear_highlite = function(self)
			self.bgcolor = "255 255 255 0 *"
		end,
	}
	
	return highlite_obj
end



--primitive spacer using a frame object, mimics html <hr> kinda
--its actually a complex, but bite me
he.page_rule = function(intable)
	local default = {
		orientation = "HORIZONTAL", -- or "VERTICAL"
		thickness = 2,
		color = "150 150 150 255 *", -- optional
	}

	for k, v in pairs(intable) do
		default[k] = v
	end

	local size = (default.orientation == "HORIZONTAL")
		and tostring(default.thickness) .. "x1"
		or "1x" .. tostring(default.thickness)

	local frame = iup.label {
		title = "",
		expand = (default.orientation == "HORIZONTAL") and "HORIZONTAL" or "VERTICAL",
		font = default.thickness,
		size = size,
		bgcolor = default.color,
	}

	return frame

end



--preset progress bar. default valuess of iup.progressbar are wierd.
--todo: add functions for async value tweening and preset images. also, just figure out things?
he.progressbar = function(intable)
	local default = {
		--uppertexture = tryfile("progress_frame.png")
		--middletexture = tryfile("??")
		--lowertexture = tryfile("??")
		
		uppercolor = "255 255 255 255 *",
		--middleabovecolor = 
		--middlebelowcolor = 
		lowercolor = "0 0 0 255 *",
		
		type = "HORIZONTAL",
		
		minvalue = 0,
		maxvalue = 100,
		value = 33,
		
		size = "200x" .. tostring(Font.Default),
	}
	
	for k, v in pairs(intable) do
		default[k] = v
	end
	
	return iup.progressbar(default)
end



he.hslider = function(intable)
	
	local scroll_timer = Timer()
		--scroll_cb is called EVERY FRAME during a drag event. if your function is heavy, use scroll_event_cb() instead. There should be an EVEN better way of doing this, but i've not found it
	local scroll_flag = false
	
	local default = {
		xmin = 0,
		xmax = 100,
		dx = 30,
		posx = 0,
		scrollbar = "HORIZONTAL",
		expand = "HORIZONTAL",
		scroll_event_cb = function() end, --called by timer when flagged with default scroll_cb()
		scroll_cb = function(self)
			scroll_flag = true
		end,
		border = "NO",
	}
	
	for k, v in pairs(intable) do
		default[k] = v
	end
	
	local scroller = iup.canvas(default)
	
	scroller.get_pos = function(self)
		return self.posx
	end
	
	scroller.get_pos_percent = function(self)
		--get percentage position
		return (self.posx / (self.xmax - self.xmin) * 100)
	end
	
	scroller.set_pos = function(self, inval)
		local clamped = math.max(self.xmin, math.min(self.xmax, tonumber(inval) or 0))
		self.posx = clamped

		if self.scroll_event_cb then
			self:scroll_event_cb()
		end
	end
	
	scroller.set_pos_percent = function(self, percent)
		local clamped = math.max(0, math.min(100, tonumber(percent) or 0))
		local range = self.xmax - self.xmin
		self.posx = (clamped / 100) * range

		if self.scroll_event_cb then
			self:scroll_event_cb()
		end
	end
	
	local scroll_update
	scroll_update = function()
		if not iup.IsValid(scroller) then
			scroll_timer:Kill()
			return
		end
		
		if scroll_flag then
			default.scroll_event_cb(scroller)
			scroll_flag = false
		end
		
		scroll_timer:SetTimeout(1, scroll_update)
	end
	
	scroller.init_timer = function(self)
		scroll_update()
	end
	
	scroller.map_cb = function(self)
		--if map_cb is replaced, this needs to be added manually to it
		self:init_timer()
	end
	
	return scroller
end

he.vslider = function(intable)
	
	local scroll_timer = Timer()
		--scroll_cb is called EVERY FRAME during a drag event. if your function is heavy, use scroll_event_cb() instead. There should be an EVEN better way of doing this, but i've not found it
	local scroll_flag = false
	
	local default = {
		ymin = 0,
		ymax = 100,
		dy = 30,
		posy = 0,
		scrollbar = "VERTICAL",
		expand = "VERTICAL",
		scroll_event_cb = function() end, --called by timer when flagged with default scroll_cb()
		scroll_cb = function(self)
			scroll_flag = true
		end,
		border = "NO",
	}
	
	for k, v in pairs(intable) do
		default[k] = v
	end
	
	local scroller = iup.canvas(default)
	
	scroller.get_pos = function(self)
		return self.posy
	end
	
	scroller.get_pos_percent = function(self)
		--get percentage position
		return (self.posy / (self.ymax - self.ymin) * 100)
	end
	
	scroller.set_pos = function(self, inval)
		local clamped = math.max(self.ymin, math.min(self.ymax, tonumber(inval) or 0))
		self.posy = clamped

		if self.scroll_event_cb then
			self:scroll_event_cb()
		end
	end
	
	scroller.set_pos_percent = function(self, percent)
		local clamped = math.max(0, math.min(100, tonumber(percent) or 0))
		local range = self.ymax - self.ymin
		self.posy = (clamped / 100) * range

		if self.scroll_event_cb then
			self:scroll_event_cb()
		end
	end
	
	local scroll_update
	scroll_update = function()
		if not iup.IsValid(scroller) then
			scroll_timer:Kill()
			return
		end
		
		if scroll_flag then
			default.scroll_event_cb(scroller)
			scroll_flag = false
		end
		
		scroll_timer:SetTimeout(1, scroll_update)
	end
	
	scroller.init_timer = function(self)
		scroll_update()
	end
	
	scroller.map_cb = function(self)
		--if map_cb is replaced, this needs to be added manually to it
		self:init_timer()
	end
	
	return scroller
end



--single-button toggle that switches between options when pressed
he.cycle_button = function(intable)
	local default = {
		base = iup.stationbutton,
		action = function(self)
			
		end,
		default = 1,
		[1] = "Untitled",
	}
	
	for k, v in pairs(intable) do
		default[k] = v
	end
	
	local get_longest = function()
		--doesn't actually get LONGEST string, just one with most chars
		local longest = 0
		local longest_index = -1
		for k, v in ipairs(default) do
			local length = string.len(v)
			if length > longest then
				longest_index = k
				longest = length
			end
		end
		
		return longest_index
	end
	
	local cycle_button = default.base {
		title = default[get_longest()],
		index = default.default,
		map_cb = function(self)
			self.size = tostring(self.w) .. "x" .. tostring(self.h)
			self.title = default[tonumber(self.index)]
		end,
		action = function(self)
			self.index = tonumber(self.index) + 1
			if tonumber(self.index) > #default then
				self.index = 1
			end
			self.title = default[tonumber(self.index)]
			default.action(self, tonumber(self.index))
		end,
	}
	
	cycle_button.get_index = function(self) return tonumber(self.index) end
	cycle_button.set_index = function(self, i)
		self.index = math.max(1, math.min(#default, tonumber(i) or 1))
		self.title = default[self.index]
	end
	
	return cycle_button
end



--motion capture object
he.motion_capture = function(intable)

	local motion_timer = Timer()
	local motion_flag = false

	local latest_x
	local latest_y
	local latest_status

	local default = {
		expand = "YES",
		size = "1x1",
		border = "NO",

		event_delay = 1,
		track_motion = "YES",

		-- called for ALL button actions
		action_feedback_cb = function(self, data)

		end,

		-- convenience callback for button press
		press_feedback_cb = function(self, data)

		end,

		-- convenience callback for button release
		release_feedback_cb = function(self, data)

		end,

		-- throttled motion callback
		motion_feedback_cb = function(self, data)

		end,
	}

	for k, v in pairs(intable or {}) do
		default[k] = v
	end

	local capture = iup.canvas {
		expand = default.expand,
		size = default.size,
		border = default.border,

		gesture_id = 0,
		gesture = nil,

		button_cb = function(self, button, pressed, x, y, status)

			local w = tonumber(self.w) or 1
			local h = tonumber(self.h) or 1

			local data = {
				button = button,
				pressed = pressed,

				x = x,
				y = y,

				x_percent = (x / w) * 100,
				y_percent = (y / h) * 100,

				status = status,
			}

			-- universal callback
			default.action_feedback_cb(self, data)

			if pressed == 1 then

				self.gesture_id = self.gesture_id + 1

				self.gesture = {
					id = self.gesture_id,

					start_x = x,
					start_y = y,

					last_x = x,
					last_y = y,
				}

				data.gesture_id = self.gesture.id
				data.phase = "press"

				default.press_feedback_cb(self, data)

			else

				if self.gesture then

					local total_dx = x - self.gesture.start_x
					local total_dy = y - self.gesture.start_y

					data.gesture_id = self.gesture.id
					data.phase = "release"

					data.total_dx = total_dx
					data.total_dy = total_dy

					data.total_dx_percent = (total_dx / w) * 100
					data.total_dy_percent = (total_dy / h) * 100
				end

				default.release_feedback_cb(self, data)

				self.gesture = nil
			end
		end,

		motion_cb = function(self, x, y, status)

			if default.track_motion ~= "YES" then
				return
			end

			if not self.gesture then
				return
			end

			latest_x = x
			latest_y = y
			latest_status = status

			motion_flag = true
		end,
	}

	local motion_update

	motion_update = function()

		if not iup.IsValid(capture) then
			motion_timer:Kill()
			return
		end
		
		if capture.visible == "NO" then
			motion_timer:SetTimeout(default.event_delay, motion_update)
			return
		end

		if motion_flag and capture.gesture then

			local gesture = capture.gesture

			local x = latest_x
			local y = latest_y

			local dx = x - gesture.last_x
			local dy = y - gesture.last_y

			local total_dx = x - gesture.start_x
			local total_dy = y - gesture.start_y

			gesture.last_x = x
			gesture.last_y = y

			motion_flag = false

			local w = tonumber(capture.w) or 1
			local h = tonumber(capture.h) or 1

			local data = {
				gesture_id = gesture.id,
				phase = "motion",

				x = x,
				y = y,

				x_percent = (x / w) * 100,
				y_percent = (y / h) * 100,

				dx = dx,
				dy = dy,

				dx_percent = (dx / w) * 100,
				dy_percent = (dy / h) * 100,

				total_dx = total_dx,
				total_dy = total_dy,

				total_dx_percent = (total_dx / w) * 100,
				total_dy_percent = (total_dy / h) * 100,

				status = latest_status,
			}

			default.motion_feedback_cb(capture, data)
		end

		motion_timer:SetTimeout(default.event_delay, motion_update)
	end

	capture.init_timer = function(self)
		motion_update()
	end

	capture.map_cb = function(self)
		self:init_timer()
	end

	return capture
end





public.primitives = he